//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalReportDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee1
    {
        public int EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Sex { get; set; }
        public int? age { get; set; }
        public int? DepartmentID { get; set; }
        public int? SalaryID { get; set; }
    }
}
